name: Recover Issues

on:
  push:
    paths:
      - 'recover_issues/*.md'  # 监听 recover_issues 文件夹下的所有 .md 文件
  workflow_dispatch:  # 支持手动触发

jobs:
  recover-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requests package
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to reopen issues
        run: |
          python restore_issues.py